# Definition of QA pipeline at SonarSource

TEST:
  - plugin
  - ruling
  - ci

SQ_VERSION:
  - DOGFOOD
  - LATEST_RELEASE
  - LATEST_RELEASE[6.7]

exclude:

  - SLAVE: linux
    TEST: ci

  - TEST: ruling
    SLAVE: linux
    SQ_VERSION: LATEST_RELEASE

  - TEST: ruling
    SLAVE: linux
    SQ_VERSION: LATEST_RELEASE[6.7]

  - SLAVE: windows
    TEST: ruling

  - TEST: plugin
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE

  - TEST: plugin
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE[6.7]

  - TEST: ci
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE

  - TEST: ci
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE[6.7]
