# Definition of QA pipeline at SonarSource

TEST:
  - plugin
  - ruling
  - ci

SQ_VERSION:
  - DEV
  - LATEST_RELEASE
  - LATEST_RELEASE[6.7]

exclude:

  - SLAVE: linux
    TEST: ci

  - TEST: ci
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE

  - TEST: ci
    SLAVE: windows
    SQ_VERSION: LATEST_RELEASE[6.7]

