# Definition of QA pipeline at SonarSource

TEST:
  - plugin
  - ruling
  - ci

SQ_VERSION:
  - DEV
  - LATEST_RELEASE
  - LATEST_RELEASE[6.7]

SLAVE:
  - windows
  - linux

exclude:

  - SLAVE: linux
    TEST: ci

  - SLAVE: windows
    TEST: ruling
